config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'pages#home'

  get "home" => "pages#home"
  get "about" => "pages#about"
  get "account" => "pages#account"
  get "index" => "pages#index"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/auth/failure", to: "sessions#omniauth_failure"

  get "/signout" => "sessions#destroy", :as => :signout

  resources :trips

end

app/models/b_cycle_station.rb
class BCycleStation < ActiveRecord::Base

  geocoded_by :full_street_address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  def address_changed?
    address_parts = ['address_line1', 'city', 'state', 'zip']
    address_parts.any?{|a| send "#{a}_changed?"}
  end

  # private

  def full_street_address
    "#{address_line1} #{city} #{state} #{zip}"
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  # belongs_to :trip_segment

  geocoded_by :address
  after_validation :geocode

  # validates :latitude, :longitude, presence: true

  def self.update_lat_longs
    self.where(latitude: nil).each(&:save)
  end

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :starting_location,    class_name: "Location"
  belongs_to :destination_location, class_name: "Location"

  belongs_to :user

  # validates :starting_location_id, :destination_location_id, presence: true


    # def self.start_lat
    #   self.starting_location.latitude
    # end


  end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trips

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider    = auth["provider"]
      user.uid         = auth["uid"]
      user.first_name  = auth["info"]["first_name"]
      user.last_name   = auth["info"]["last_name"]
      user.email       = auth.info.email
      user.picture_url = auth.info.picture
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :require_login, except: [:home, :about]

  def home
  end

  def about
  end

  def account
  end

  def index
    @dest_add     = current_user.trips.last.destination_location.address
    @dest_add_lat = current_user.trips.last.destination_location.latitude
    @dest_add_lon = current_user.trips.last.destination_location.longitude

    @uber_time = Uber.new.get_time_estimate(current_user.trips.last.starting_location.latitude,
                                            current_user.trips.last.destination_location.longitude)
    @uber_trip = Uber.new.get_uber_trip(current_user.trips.last.starting_location.latitude,
                                        current_user.trips.last.starting_location.longitude,
                                        current_user.trips.last.destination_location.latitude,
                                        current_user.trips.last.destination_location.longitude)
    if @uber_trip != '-'
      @uber_price      = "#{@uber_trip[:uber_low_price]} - #{@uber_trip[:uber_hi_price]}"
      @uber_ride_time  = @uber_trip[:uber_trip_time] / 60
      @uber_total_time = @uber_time + @uber_ride_time
      @uber_surge      = @uber_trip[:surge_multiplier]

      @car2go_price    = ((@uber_trip[:uber_trip_time] / 60) * 0.41).round(2) #calc based on uber for now
    else
      @uber_price      = '-'
      @uber_ride_time  = '-'
      @uber_total_time = '-'
      @uber_surge      = 0

      @car2go_price    = '-'
    end

    @car2go = Car2go.get_cars
    @b_cycle_stations = BCycleStation.all
  end

private

  def require_login
    unless current_user
      flash[:error] = "You must log in with UBER to build a trip"
      redirect_to root_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    user.save
    if user.save
      redirect_to new_trip_path#, notice: "You successfully signed in."
      flash[:notice] = "You successfully signed in."
    else
      omniauth_failure
    end
  end

  def omniauth_failure
    redirect_to root_url#, notice: "UBER authentication failed."
    flash[:failure] =  'UBER authentication failed.'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url#, notice: "You successfully signed out."
    flash[:log_out] =  'You successfully logged out.'
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :require_login

  def new
    @trip = Trip.new
  end

  def create
    start_location = Location.create(latitude: params[:starting_location][:latitude],
                                     longitude: params[:starting_location][:longitude])

    dest_location  = Location.create(address: params[:destination_location][:address])

    trip = Trip.create(starting_location:    start_location,
                       destination_location: dest_location,
                       user:                 current_user)
    if trip.save
      redirect_to '/index'
    else
      render :new, notice: "Destination invalid."
    end
  end

private

  def require_login
    unless current_user
      flash[:error] = "You must log in with UBER to build a trip"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <% if flash.notice %>
    <div data-alert class="alert-box success">
      <%= notice %>
      <a href="#" class="close">&times;</a>
    </div>
  <% elsif flash[:failure] %>
    <div data-alert class="alert-box failure">
      <%= flash[:failure] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% elsif flash[:log_out]  %>
    <div data-alert class="alert-box warning">
      <%= flash[:log_out] %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="sticky">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1 class="raleway"><a href="/home">local motion</a></h1>
      </li>
       <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <% if current_user %>
        <ul class="right">
          <!-- <li class="active"><a href="#">sign out</a></li> -->
          <li class="has-dropdown">
            <a href="#">Welcome <%= current_user.first_name %></a>
            <ul class="dropdown">
              <li><%= link_to "account", account_path(current_user) %></li>
              <!-- <li><a href="/account">account</a></li> -->
              <li class="active"><a href="/signout">sign out</a></li>
            </ul>
          </li>
        </ul>
      <% end %>

      <!-- <ul class="left">
        <li><a href="/about">how it works</a></li>
      </ul> -->
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "local motion" %></title>

    <link href='https://fonts.googleapis.com/css?family=Syncopate' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true?key=AIzaSyBaK_7Mwsr60nrhZx1d-aEkIkGvUo4d6m8"></script>
  </head>

  <body>

    <%= render partial: 'layouts/navbar' %>
    <%= render partial: 'layouts/flash' %>

    <!-- <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %> -->

    <%= yield %>
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>

app/views/pages/account.html.erb
<h1><%= current_user.first_name %>'s Account</h1>

app/views/pages/home.html.erb
<% if current_user %>

  <div id="bg">
    <div id="welcome-container">
      <div id="welcome-bg"></div>
      <div id="welcome">
        <h2 class="raleway">Get started:</h2>
          <%= link_to "Use My Location", new_trip_path, {:class=>"button [secondary success alert]" } %>
      </div>
    </div>
  </div>

<% else %>

  <div class="title_text">local motion</div>
  <div id="bg">
    <div id="welcome-container">
      <div id="welcome-bg"></div>
      <div id="welcome">
        <h2 class='raleway'>See the best rideshare options nearest you</h2>
        <%= link_to "Log in with UBER", '/auth/uber', {:class=>"button [secondary success alert]" } %>
      <div class="raleway" id="free_30_call"><a href="/#free_30">Sign Up With a Free Trip</a></div>
      </div>
    </div>
  </div>

<div class="below_title"></div>
  <div class="solid_background">
    <div class="description_title raleway">Get Moving</div>
    <div class="description_content">
      local motion is the best way to see your options when it comes to making a
      quick local trip around town.
      local motion shows you what rideshare options are closest to your current
      location and breaks each one down based on time and price estimates for your
      trip.

      </br></br><strong>Currently Serving Denver</strong>
      The most popular ride sharing options in Denver that we are providing are:
      UBER, car2go, and B-cycle.
      We love our Denver folk and are working to create the best possible experience
      for you. local motion is currently only available in Denver, but don't fret
      if you're not one of the Denver elite, we'll be expanding soon. To be notified
      when we launch in your city, just enter your email here:
      <strong><a href="#" data-reveal-id="myModal">Notify Me</a></strong>

        <div id="myModal" class="reveal-modal" data-reveal>
          <h2> Be first to know when <span class='raleway'>local motion</span> drops in your city</h2>

          <form>
            <div class="row">
              <div class="large-12 columns">
                  <input type="text" placeholder="email" />
              </div>
            </div>
            <div class="row">
              <div class="large-4 columns">
                <label>Your City:
                  <input type="text" placeholder="City, State" />
                </label>
              </div>
            </div>
            <div class="row">
            </div>
              <div class="large-6 columns">
                <label>Stay connected with our mailing letter:</label>
                <input id="checkbox1" type="checkbox"><label for="checkbox1">Awesome!</label>
              </div>
              <a href="#" class="button [radius round]">Tell Me!</a>
          </form>

          <a class="close-reveal-modal">&#215;</a>
            </div>
        </div>
    </div>
    </div>

    <h1 class="middle_pic raleway">
      </br></br></br><strong>The shortest distance between two points</strong>
    </h1>

    <div class="description_title raleway" id="free_30">First Ride Free</div>
    <div class="description_content">
      <strong>Don't have an UBER account?</strong></br>
      Sign up today and receive a $20 credit toward UBER and get moving with
      local motion today:
      <strong><a href="https://www.uber.com/invite/uberlocalmotion">Get $20</a></strong>
    </div>
  </div>

  <div class="footer raleway">
  </br>
    <p>
      Developed by <a href="https://twitter.com/eric_fransen">Eric Fransen</a>.
      This app uses APIs by but is not endorsed or certified by: UBER, car2go, B-cycle.
    </p>
  </div>

<% end %>

app/views/pages/index.html.erb
<div class="index_background">
  <div class="show_map">
    <div id="map-canvas"></div>
  </div>

  <div id="sidebar">
    <div id="profile">
      <%= image_tag current_user.picture_url, class: 'profile_pic' %>
      <!--<img src='<%= current_user.picture_url %>' alt="UBER Profile Pic" class="profile_pic">-->
      <h5 class='raleway'><%= @current_user.first_name %></h5>
      <input class="dest_input" placeholder="<%= @dest_add %>" autofocus>
    </div>

    <div id="bcycle" class="row">
      <div class="service-logo small-3 large-3 columns">
        <a href="#" data-reveal-id="bcycle_Modal">
          <div class="bcycle_logo"></div>
          <!-- <%= image_tag("b_cycle_logo.jpg") %> -->
          <!-- <img src="/assets/b_cycle_logo.jpg" alt="B-cycle Logo" class="bcycle_logo"> -->
        </a>
      </div>
      <div id="bcycle_price" class="service-price small-4 large-4 columns">
        <h2>$</h2>
        <h3><%= '8' %></h3>
      </div>
      <div class="service-time small-5 large-5 columns">
        <ul>
          <h3 class="bcycle_style"><strong><%= '-' %> MIN</strong></h3>
          <li><%= '-' %> MIN walk</li>
          <li><%= '-' %> MIN ride</li>
          <li><%= '-' %> MIN walk</li>
        </ul>
      </div>

      <div class="service-actions">
        <!-- <a href="#" data-reveal-id="myModal">GO</a> -->
        <div id="bcycle_Modal" class="reveal-modal" data-reveal>
          <h2 class='raleway'>B-cycle Settings</h2>
          <div class="large-6 columns">
            <label>I'm a current B-cycle member:</label>
            <input id="checkbox1" type="checkbox"><label for="checkbox1">Sure Am</label>
          </div>
          <p class='lead raleway'>B-cycle does not provide the ability to reserve B-cycles remotely.</p>
          <p class='raleway'>If you are not a current B-cycle member, you can sign up here:</p>
          <a href="https://denver.bcycle.com/joinnow.aspx" class="button [tiny]">Sign Up</a>
          <a class="close-reveal-modal">&#215;</a>
        </div>
      </div>
    </div>


    <div id="car2go" class="row">
      <div class="service-logo small-3 large-3 columns">
        <a href="#" data-reveal-id="car2go_Modal">
          <!-- <img src="/assets/car2go_logo.png" alt="car2go Logo" class="car2go_logo"> -->
          <!-- <%= image_tag("car2go_logo.png") %> -->
          <div class="car2go_logo"></div>
        </a>
      </div>
      <div id="car2go_price" class="service-price small-4 large-4 columns">
        <h2>$</h2>
        <h3><%= @car2go_price %></h3>
      </div>
      <div class="service-time small-5 large-5 columns">
        <ul>
          <h3 class="car2go_style"><strong><%= '-' %> MIN</strong></h3>
          <li><%= '-' %> MIN walk</li>
          <li><%= '-' %> MIN drive</li>
        </ul>
      </div>

      <div class="service-actions">
        <!-- <a href="#" data-reveal-id="myModal">GO</a> -->
        <div id="car2go_Modal" class="reveal-modal" data-reveal>
          <h2 class='raleway'>Reserve a car2go</h2>
          <p class='lead raleway'>Ability to reserve a car2go through this app is unavailable at this time.</p>
          <p class='raleway'>This feature is coming soon, in the meantime click here to reserve:</p>
          <a href="https://play.google.com/store/apps/details?id=com.car2go&hl=en" class="button [tiny]">Android</a>
          <a href="https://itunes.apple.com/us/app/car2go/id514921710?mt=8" class="button [tiny]">Apple</a>
          <a class="close-reveal-modal">&#215;</a>
        </div>
      </div>
    </div>







    <div id="uber" class="row">
      <div class="service-logo small-3 large-3 columns">
        <a href="#" data-reveal-id="uber_Modal">
          <div class="uber_logo"></div>
          <!-- <img src="/assets/uber_logo.png" alt="UBER Logo" class="uber_logo"> -->
          <!-- <%= image_tag("uber_logo.png") %> -->
        </a>
      </div>
      <div id="uber_price" class="service-price small-4 large-4 columns">
        <h2>$</h2>
        <h3><%= @uber_price %></h3>
        <% if @uber_surge > 1 %>
          <h5>surge <%= @uber_surge %>x</h5>
        <% end %>
      </div>
      <div class="service-time small-5 large-5 columns">
        <ul>
          <h3 class="uber_style"><strong><%= @uber_total_time %> MIN</strong></h3>
          <li><%= @uber_time %> MIN wait</li>
          <li><%= @uber_ride_time %> MIN ride</li>
        </ul>
      </div>

      <div class="service-actions">
        <!-- <a href="#" data-reveal-id="myModal">GO</a> -->
        <div id="uber_Modal" class="reveal-modal" data-reveal>
          <h2 class='raleway'>Book an UBER</h2>
          <p class='lead raleway'>Ability to book UBER through this app is unavailable at this time.</p>
          <p class='raleway'>This feature is coming soon, in the meantime click here to book:</p>
          <a href="https://play.google.com/store/apps/details?id=com.ubercab&hl=en" class="button [tiny]">Android</a>
          <a href="https://itunes.apple.com/us/app/uber/id368677368?mt=8" class="button [tiny]">Apple</a>
          <a class="close-reveal-modal">&#215;</a>
        </div>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    var locations = [
    <% @car2go.each do |car| %>
      ["<%= car["address"] %>",
        <%= car["coordinates"][1] %>,
        <%= car["coordinates"][0] %>,
       "<%= car["name"] %>",
       "<%= car["interior"] %>",
       "<%= car["exterior"] %>",
       "<%= car["fuel"] %>"],
    <% end %>
    ];

    var bCycles = [
    <% @b_cycle_stations.each do |bcycle| %>
      ["<%= bcycle.station_name %>",
        <%= bcycle.num_docks %>,
        <%= bcycle.latitude %>,
        <%= bcycle.longitude %>,
       "<%= bcycle.full_street_address %>"],
    <% end %>
    ];

    var destAddLat = "<%= @dest_add_lat %>";
    var destAddLon = "<%= @dest_add_lon %>";
  </script>
</div>

app/views/trips/new.html.erb
<div id="bg"></div>


<%= form_for @trip do |f| %>
  <%= fields_for :starting_location, @trip.starting_location do |start| %>
    <%= start.hidden_field :latitude %>
    <%= start.hidden_field :longitude %>
    <!-- <%= start.label :address %>: -->
    <%= start.text_field :address %><br />
  <% end %>
  <div class="row">
    <div class="large-12 columns">
      <div class="row collapse">
        <div class="small-10 columns">
          <%= fields_for :destination_location, @trip.destination_location do |destination| %>
            <!-- <%= destination.hidden_field :latitude %>
            <%= destination.hidden_field :longitude %> -->
            <!-- <%= destination.label :address %>: -->
            <%= destination.text_field :address, placeholder: "enter your destination" %><br />
          <% end %>
        </div>
        <div class="small-2 columns">
          <%= f.submit 'Go', :class => 'button postfix' %>
        <% end %>
        </div>
      </div>
    </div>
  </div>